language: python
python:
- '2.7'
install:
- pip install python-coveralls virtualenv tox
script: tox
after_success:
- pip install -r requirements-testing.txt -e .
- py.test --cov=timeout_decorator --cov-report=term-missing tests
- coveralls
deploy:
  provider: pypi
  user: png
  password:
    secure: ZXoq3kgfu+IICjhhmQZr0s0xE6bvWzH04GjdE/VL4BxdDdGI4fHEwudGEjzLXJbt2d09vNOO67Nqam+MwPWtq+WZEP69g/Fhyy4kbkuUl/CMeqashQzU/N+3lwv97Y2qvzTUwDnSoz4zyBFu67SSrovKruFsYaiH00bwvWcvLa0=
  on:
    python: 3.4
